# calculus - volumes_of_revolution (very_hard)
# Generated: 2026-03-08T20:49:27.873261

include(joinpath(@__DIR__, "..", "julia", "src", "ProblemUtils.jl"))
using .ProblemUtils

@script x begin
    set_topic!("calculus/volumes_of_revolution")
    
    problem_type = rand(1:4)
    
    if problem_type == 1
        # Competition: Volume of revolution with parametric curve or piecewise integrand
        # revolving around non-standard axis
        a = nonzero(1, 4)
        b = nonzero(1, 3)
        axis_shift = rand([-2, -1, 1, 2])
        
        # Function: y = sqrt(ax) from 0 to b, revolved around y = axis_shift
        # Washer method: V = π ∫[R(x)² - r(x)²]dx
        upper = b^2 // a
        
        # R(x) = sqrt(ax) - axis_shift (outer radius)
        # r(x) = |axis_shift| (inner radius to axis)
        
        if axis_shift < 0
            R_expr = "\\sqrt{$(a)x} - ($(axis_shift))"
            r_val = -axis_shift
        else
            R_expr = "\\sqrt{$(a)x} - $(axis_shift)"
            r_val = axis_shift
        end
        
        # V = π ∫₀^upper [(√(ax) - axis_shift)² - (axis_shift)²] dx
        # = π ∫₀^upper [ax - 2*axis_shift*√(ax) + axis_shift² - axis_shift²] dx
        # = π ∫₀^upper [ax - 2*axis_shift*√(ax)] dx
        
        # Integrate: [ax²/2 - 2*axis_shift*(2/3)*a^(1/2)*x^(3/2)]₀^upper
        term1 = a * upper^2 // 2
        term2 = (4//3) * axis_shift * sqrt(a) * upper^(3//2)
        
        volume_exact = rationalize(Float64(term1 - term2))
        ans = volume_exact
        
        problem(
            question="Find the volume of the solid obtained by revolving the region bounded by \\(y = \\sqrt{$(a)x}\\), \\(y = 0\\), and \\(x = $(upper)\\) about the line \\(y = $(axis_shift)\\). Express your answer as an exact multiple of \\(\\pi\\).",
            answer=ans,
            difficulty=(2500, 2800),
            solution=steps(
                "Set up using the washer method: \\(V = \\pi \\int_0^{$(upper)} [R(x)^2 - r(x)^2]\\,dx\\)",
                "Outer radius: \\(R(x) = $(R_expr)\\), Inner radius: \\(r(x) = $(abs(axis_shift))\\)",
                "\\(V = \\pi \\int_0^{$(upper)} [(\\sqrt{$(a)x} - $(axis_shift))^2 - $(axis_shift^2)]\\,dx\\)",
                "Expand and simplify the integrand",
                "Evaluate the integral to get \\(V = $(ans)\\pi\\)"
            ),
            time=300
        )
        
    elseif problem_type == 2
        # Competition-Olympiad: Shell method with tricky bounds or composition
        # Revolve region between two curves around y-axis
        k = nonzero(1, 3)
        n = randint(2, 4)
        upper = randint(2, 5)
        
        # Region: between y = kx and y = x^n from x=0 to x=upper, revolve around y-axis
        # Shell method: V = 2π ∫ x[f(x) - g(x)] dx
        
        if k * upper > upper^n
            top_func = "$(k)x"
            bot_func = "x^{$(n)}"
            height_expr = "$(k)x - x^{$(n)}"
        else
            top_func = "x^{$(n)}"
            bot_func = "$(k)x"
            height_expr = "x^{$(n)} - $(k)x"
        end
        
        # V = 2π ∫₀^upper x|kx - x^n| dx
        # = 2π ∫₀^upper |kx² - x^(n+1)| dx
        
        term1_coeff = k
        term1_power = 3
        term2_power = n + 2
        
        # ∫ x(kx - x^n) dx = k*x³/3 - x^(n+2)/(n+2)
        val1 = (k * upper^3) // 3
        val2 = upper^(n+2) // (n+2)
        
        volume_coeff = abs(val1 - val2) * 2
        ans = volume_coeff
        
        problem(
            question="Find the volume of the solid generated by revolving the region bounded by \\(y = $(top_func)\\), \\(y = $(bot_func)\\), and \\(x = $(upper)\\) about the \\(y\\)-axis. Express your answer as an exact multiple of \\(\\pi\\).",
            answer=ans,
            difficulty=(2600, 3000),
            solution=steps(
                "Use the cylindrical shell method: \\(V = 2\\pi \\int_0^{$(upper)} x \\cdot h(x)\\,dx\\)",
                "Height of shell: \\(h(x) = $(height_expr)\\)",
                "Set up integral: \\(V = 2\\pi \\int_0^{$(upper)} x($(height_expr))\\,dx\\)",
                "Expand and integrate term by term",
                "Evaluate at bounds to obtain \\(V = $(ans)\\pi\\)"
            ),
            time=280
        )
        
    elseif problem_type == 3
        # Olympiad: Volume with curve requiring substitution or cross-sectional area method
        # Solid with cross sections perpendicular to axis
        base = randint(3, 6)
        
        # Base region: semicircle of radius r, or triangle, with cross sections as squares/triangles
        cross_section_type = choice(["square", "equilateral_triangle", "semicircle"])
        
        # Region: under y = √(base² - x²) from -base to base (semicircle)
        # Cross sections perpendicular to x-axis
        
        if cross_section_type == "square"
            # Side length = 2y = 2√(base² - x²)
            # Area = 4(base² - x²)
            # V = ∫_{-base}^{base} 4(base² - x²) dx
            integrand_desc = "4($(base^2) - x^2)"
            area_formula = "s^2 = [2\\sqrt{$(base^2) - x^2}]^2"
            
            # = 4[base²x - x³/3] from -base to base
            val_pos = 4 * (base^3 - base^3//3)
            val_neg = 4 * (-base^3 + base^3//3)
            ans = val_pos - val_neg
            
        elseif cross_section_type == "equilateral_triangle"
            # Side = 2y, Area = (√3/4)s² = √3(base² - x²)
            integrand_desc = "\\sqrt{3}($(base^2) - x^2)"
            area_formula = "\\frac{\\sqrt{3}}{4}s^2 = \\sqrt{3}($(base^2) - x^2)"
            
            val_pos = (base^3 - base^3//3)
            val_neg = (-base^3 + base^3//3)
            ans = sqrt(3) * (val_pos - val_neg)
            
        else  # semicircle
            # Diameter = 2y, radius = y, Area = πy²/2 = π(base² - x²)/2
            integrand_desc = "\\frac{\\pi}{2}($(base^2) - x^2)"
            area_formula = "\\frac{\\pi r^2}{2} = \\frac{\\pi}{2}($(base^2) - x^2)"
            
            val_pos = (base^3 - base^3//3) // 2
            val_neg = (-base^3 + base^3//3) // 2
            ans = (val_pos - val_neg)
        end
        
        problem(
            question="A solid has a circular base of radius $(base). Cross sections perpendicular to the \\(x\\)-axis are $(cross_section_type)s with one side in the base. The base is the region \\(x^2 + y^2 \\leq $(base^2)\\), \\(y \\geq 0\\). Find the volume of the solid.",
            answer=ans,
            difficulty=(2800, 3200),
            solution=steps(
                "The base boundary is \\(y = \\sqrt{$(base^2) - x^2}\\) for \\(x \\in [-$(base), $(base)]\\)",
                "Cross-sectional area: \\(A(x) = $(area_formula)\\)",
                "Volume: \\(V = \\int_{-$(base)}^{$(base)} $(integrand_desc)\\,dx\\)",
                "Evaluate the integral using symmetry and power rule",
                sol("Answer", ans)
            ),
            time=320
        )
        
    else  # problem_type == 4
        # Olympiad: Revolving a region requiring decomposition or advanced technique
        a = nonzero(2, 5)
        
        # Revolve region bounded by y² = ax and x = a around x-axis
        # This gives a paraboloid cap
        # Use disk method: V = π ∫₀^a y² dx = π ∫₀^a ax dx
        
        ans = (a^3) // 2
        
        problem(
            question="Find the volume of the solid obtained by revolving the region bounded by the parabola \\(y^2 = $(a)x\\) and the line \\(x = $(a)\\) about the \\(x\\)-axis. Express your answer as an exact multiple of \\(\\pi\\).",
            answer=ans,
            difficulty=(3000, 3400),
            solution=steps(
                "The region is bounded by \\(y = \\pm\\sqrt{$(a)x}\\) from \\(x = 0\\) to \\(x = $(a)\\)",
                "Using the disk method: \\(V = \\pi \\int_0^{$(a)} R^2(x)\\,dx\\) where \\(R(x) = \\sqrt{$(a)x}\\)",
                "\\(V = \\pi \\int_0^{$(a)} $(a)x\\,dx = \\pi \\cdot $(a) \\cdot \\frac{x^2}{2}\\Big|_0^{$(a)}\\)",
                "Evaluate: \\(V = \\pi \\cdot $(a) \\cdot \\frac{$(a^2)}{2} = \\frac{$(a^3)\\pi}{2}\\)",
                sol("Answer", ans)
            ),
            time=300
        )
    end
end