# calculus - volumes_of_revolution (competition)
# Generated: 2026-03-08T20:49:42.098056

include(joinpath(@__DIR__, "..", "julia", "src", "ProblemUtils.jl"))
using .ProblemUtils

@script x y begin
    set_topic!("calculus/volumes_of_revolution")
    
    problem_type = choice(1:5)
    
    if problem_type == 1
        # Olympiad: Volume with parametric curve revolution
        t = only(@variables t)
        a = randint(2, 5)
        b = randint(2, 5)
        n = randint(3, 5)
        
        # Parametric: x(t) = a*t^n, y(t) = b*t^m where relation creates solvable integral
        m = randint(2, 4)
        t_max = randint(1, 3)
        
        x_param = a * t^n
        y_param = b * t^m
        
        # Revolve around x-axis: V = π∫[0,t_max] y² dx/dt dt
        dx_dt = diff(x_param, t)
        integrand = y_param^2 * dx_dt
        integrand_simplified = expand(integrand)
        
        # Compute symbolically
        integral_result = simplify(integrate(integrand_simplified, (t, 0, t_max)))
        volume = simplify(π * integral_result)
        
        question = "A curve is defined parametrically by \$x(t) = $(tex(x_param))\$ and \$y(t) = $(tex(y_param))\$ for \$0 \\leq t \\leq $(t_max)\$. Find the exact volume of the solid obtained by revolving this curve about the x-axis."
        
        solution_text = steps(
            "Parametric curve: \$x(t) = $(tex(x_param)), y(t) = $(tex(y_param))\$",
            sol("Volume formula", "V = \\pi \\int_0^{$(t_max)} y^2 \\frac{dx}{dt} \\, dt"),
            sol("\\frac{dx}{dt}", dx_dt),
            sol("Integrand", "y^2 \\frac{dx}{dt} = $(tex(integrand_simplified))"),
            "Integrate with respect to t from 0 to $(t_max)",
            sol("Volume", volume)
        )
        
        problem(
            question=question,
            answer=volume,
            difficulty=(3500, 4200),
            solution=solution_text,
            time=480
        )
        
    elseif problem_type == 2
        # Research-adjacent: Volume of revolution with algebraic curve requiring substitution
        a = randint(2, 4)
        b = randint(2, 4)
        c = randint(1, 3)
        
        # Curve: y^2 = x^3 + ax + b, revolve around y-axis from x=0 to x=c
        # V = 2π∫ x·y dx = 2π∫ x·√(x³+ax+b) dx
        
        expr_under_sqrt = x^3 + a*x + b
        
        # For exact answer, construct so integral is clean
        # Use shell method: V = 2π∫[0,c] x·√(x³+ax+b) dx
        
        # Approximate volume for complex case
        integrand = x * sqrt(expr_under_sqrt)
        
        # Symbolic integration (may be complex)
        volume_expr = 2 * π * integrate(integrand, (x, 0, c))
        volume_simplified = simplify(volume_expr)
        
        question = "Consider the algebraic curve defined implicitly by \$y^2 = $(tex(expr_under_sqrt))\$ for \$y \\geq 0\$. Revolve the region bounded by this curve, the x-axis, \$x=0\$, and \$x=$(c)\$ about the y-axis using the shell method. Find the exact volume."
        
        solution_text = steps(
            sol("Given curve", "y^2 = $(tex(expr_under_sqrt))"),
            sol("Shell method", "V = 2\\pi \\int_0^{$(c)} x \\cdot y \\, dx = 2\\pi \\int_0^{$(c)} x\\sqrt{$(tex(expr_under_sqrt))} \\, dx"),
            "This requires advanced integration techniques (substitution and algebraic manipulation)",
            "After integration and simplification:",
            sol("Volume", volume_simplified)
        )
        
        problem(
            question=question,
            answer=volume_simplified,
            difficulty=(4000, 4800),
            solution=solution_text,
            time=600
        )
        
    elseif problem_type == 3
        # Olympiad: Solid of revolution with hole (washer method, complex bounds)
        a = randint(2, 4)
        b = randint(1, 3)
        c = randint(3, 6)
        
        # Outer: y = a√x, Inner: y = bx, from x=0 to intersection
        outer = a * sqrt(x)
        inner = b * x
        
        # Find intersection: a√x = bx → a = b√x → a² = b²x → x = a²/b²
        x_intersect = a^2 // b^2
        
        # Volume: π∫[0, x_intersect] (outer² - inner²) dx
        integrand = outer^2 - inner^2
        integrand_expanded = expand(integrand)
        
        volume_integral = integrate(integrand_expanded, (x, 0, x_intersect))
        volume = simplify(π * volume_integral)
        
        question = "Find the volume of the solid generated by revolving the region bounded by \$y = $(tex(outer))\$, \$y = $(tex(inner))\$, and the y-axis about the x-axis. Use the washer method."
        
        solution_text = steps(
            "Find intersection: \$$(tex(outer)) = $(tex(inner))\$",
            sol("Intersection point", "x = $(tex(x_intersect))"),
            sol("Washer method", "V = \\pi \\int_0^{$(tex(x_intersect))} \\left[($(tex(outer)))^2 - ($(tex(inner)))^2\\right] dx"),
            sol("Integrand", integrand_expanded),
            "Integrate and simplify",
            sol("Volume", volume)
        )
        
        problem(
            question=question,
            answer=volume,
            difficulty=(3600, 4300),
            solution=solution_text,
            time=540
        )
        
    elseif problem_type == 4
        # Research-adjacent: Pappus's theorem application with centroid calculation
        r = randint(2, 5)
        R = randint(r+2, r+6)
        
        # Semicircle of radius r, center at (R, 0), revolve around y-axis
        # Area of semicircle: πr²/2
        # Centroid distance from y-axis: R + 4r/(3π)
        
        area = π * r^2 // 2
        centroid_dist = R + 4*r//(3*π)
        volume = 2 * π * centroid_dist * area
        volume_simplified = simplify(volume)
        
        question = "A semicircular region of radius $(r) has its diameter along a line parallel to the y-axis at distance $(R) from it. Using Pappus's theorem, find the exact volume of the solid generated when this semicircle is revolved about the y-axis. (Recall: the centroid of a semicircle is at distance \$\\frac{4r}{3\\pi}\$ from its diameter.)"
        
        solution_text = steps(
            sol("Area of semicircle", "A = \\frac{\\pi r^2}{2} = $(tex(area))"),
            sol("Centroid from y-axis", "\\bar{x} = R + \\frac{4r}{3\\pi} = $(tex(centroid_dist))"),
            sol("Pappus's theorem", "V = 2\\pi \\bar{x} A"),
            "Substitute values",
            sol("Volume", volume_simplified)
        )
        
        problem(
            question=question,
            answer=volume_simplified,
            difficulty=(3800, 4500),
            solution=solution_text,
            time=420
        )
        
    else
        # Olympiad: Volume with transcendental function and non-standard axis
        a = randint(2, 4)
        b = randint(1, 3)
        k = randint(2, 5)
        
        # Revolve y = a·e^(bx) around line y = k, from x=0 to x=1
        # Distance from y=k: |a·e^(bx) - k|
        
        func = a * ℯ^(b*x)
        
        # Assume a > k for upper region
        # V = π∫[0,1] (a·e^(bx) - k)² dx
        
        distance_sq = (func - k)^2
        integrand = expand(distance_sq)
        
        volume_integral = integrate(integrand, (x, 0, 1))
        volume = simplify(π * volume_integral)
        
        question = "Find the exact volume of the solid obtained by revolving the region bounded by \$y = $(tex(func))\$, the lines \$x=0\$, \$x=1\$, and \$y=$(k)\$ about the horizontal line \$y=$(k)\$. Assume the curve lies above the line."
        
        solution_text = steps(
            sol("Distance from axis", "d(x) = $(tex(func)) - $(k)"),
            sol("Disk method", "V = \\pi \\int_0^1 [d(x)]^2 \\, dx = \\pi \\int_0^1 ($(tex(func - k)))^2 \\, dx"),
            sol("Expand", integrand),
            "Integrate term by term using exponential rules",
            sol("Volume", volume)
        )
        
        problem(
            question=question,
            answer=volume,
            difficulty=(3700, 4400),
            solution=solution_text,
            time=500
        )
    end
end