# calculus - volumes_of_revolution (hard)
# Generated: 2026-03-08T20:49:01.890014

include(joinpath(@__DIR__, "..", "julia", "src", "ProblemUtils.jl"))
using .ProblemUtils

@script x begin
    set_topic!("calculus/volumes_of_revolution")
    
    prob_type = rand(1:5)
    
    if prob_type == 1
        # Disk method: rotate region under curve around x-axis
        # y = sqrt(x) from x=0 to x=a, rotated around x-axis
        a = randint(4, 16)
        func = sqrt(x)
        volume = π * a^2 / 2
        
        problem(
            question="Find the volume of the solid generated by revolving the region bounded by \\(y = \\sqrt{x}\\), \\(y = 0\\), and \\(x = $(a)\\) about the \\(x\\)-axis.",
            answer=volume,
            difficulty=(1800, 2000),
            solution=steps(
                "Use the disk method: \\(V = \\pi \\int_a^b [f(x)]^2 \\, dx\\)",
                sol("Setup", "V = \\pi \\int_0^{$(a)} (\\sqrt{x})^2 \\, dx = \\pi \\int_0^{$(a)} x \\, dx"),
                sol("Integrate", "V = \\pi \\left[ \\frac{x^2}{2} \\right]_0^{$(a)} = \\pi \\cdot \\frac{$(a)^2}{2}"),
                sol("Answer", "V = $(volume)")
            ),
            time=180
        )
        
    elseif prob_type == 2
        # Washer method: rotate region between two curves around x-axis
        # Between y = sqrt(x) and y = x/k, from 0 to intersection
        k = choice([2, 3, 4])
        # Intersection: sqrt(x) = x/k => x = x^2/k^2 => x(1 - x/k^2) = 0 => x = k^2
        a = k^2
        outer = sqrt(x)
        inner = x // k
        volume = π * (a^2 / 2 - a^3 / (3 * k^2))
        
        problem(
            question="Find the volume of the solid generated by revolving the region between \\(y = \\sqrt{x}\\) and \\(y = \\frac{x}{$(k)}\\) about the \\(x\\)-axis.",
            answer=volume,
            difficulty=(2000, 2200),
            solution=steps(
                "Find intersection: \\(\\sqrt{x} = \\frac{x}{$(k)} \\Rightarrow x = $(a)\\)",
                "Use washer method: \\(V = \\pi \\int_0^{$(a)} \\left[(\\sqrt{x})^2 - \\left(\\frac{x}{$(k)}\\right)^2\\right] dx\\)",
                sol("Setup", "V = \\pi \\int_0^{$(a)} \\left(x - \\frac{x^2}{$(k^2)}\\right) dx"),
                sol("Integrate", "V = \\pi \\left[\\frac{x^2}{2} - \\frac{x^3}{$(3*k^2)}\\right]_0^{$(a)}"),
                sol("Answer", "V = $(volume)")
            ),
            time=240
        )
        
    elseif prob_type == 3
        # Shell method: rotate around y-axis
        # y = x^2 from x=0 to x=a, around y-axis
        a = randint(2, 5)
        func = x^2
        volume = π * a^4 / 2
        
        problem(
            question="Find the volume of the solid generated by revolving the region bounded by \\(y = x^2\\), \\(x = 0\\), and \\(x = $(a)\\) about the \\(y\\)-axis.",
            answer=volume,
            difficulty=(1900, 2100),
            solution=steps(
                "Use the shell method: \\(V = 2\\pi \\int_a^b x \\cdot f(x) \\, dx\\)",
                sol("Setup", "V = 2\\pi \\int_0^{$(a)} x \\cdot x^2 \\, dx = 2\\pi \\int_0^{$(a)} x^3 \\, dx"),
                sol("Integrate", "V = 2\\pi \\left[\\frac{x^4}{4}\\right]_0^{$(a)} = 2\\pi \\cdot \\frac{$(a)^4}{4}"),
                sol("Answer", "V = $(volume)")
            ),
            time=180
        )
        
    elseif prob_type == 4
        # Rotate around horizontal line y = k
        # Region: y = x from x=0 to x=a, rotated around y = -1
        a = randint(3, 8)
        k = -1
        # Outer radius: x - (-1) = x + 1, inner radius = 0 - (-1) = 1
        volume = π * (a^3/3 + a^2 + a - a)
        
        problem(
            question="Find the volume of the solid generated by revolving the region bounded by \\(y = x\\), \\(y = 0\\), and \\(x = $(a)\\) about the line \\(y = -1\\).",
            answer=volume,
            difficulty=(2100, 2300),
            solution=steps(
                "The outer radius is \\(R(x) = x - (-1) = x + 1\\)",
                "The inner radius is \\(r(x) = 0 - (-1) = 1\\)",
                sol("Setup", "V = \\pi \\int_0^{$(a)} [(x+1)^2 - 1^2] \\, dx"),
                sol("Expand", "V = \\pi \\int_0^{$(a)} (x^2 + 2x) \\, dx"),
                sol("Integrate", "V = \\pi \\left[\\frac{x^3}{3} + x^2\\right]_0^{$(a)} = \\pi\\left(\\frac{$(a)^3}{3} + $(a)^2\\right)"),
                sol("Answer", "V = $(volume)")
            ),
            time=240
        )
        
    else
        # Complex washer: parabola and line
        # y = 4 - x^2 and y = 0, from x = -a to x = a, around x-axis
        a = randint(2, 4)
        volume = π * (16*a - (8*a^3)/3 + a^5/5)
        
        problem(
            question="Find the volume of the solid generated by revolving the region bounded by \\(y = 4 - x^2\\) and \\(y = 0\\) about the \\(x\\)-axis.",
            answer=volume,
            difficulty=(2000, 2200),
            solution=steps(
                "The curve intersects \\(y = 0\\) when \\(4 - x^2 = 0\\), so \\(x = \\pm 2\\)",
                "Use disk method: \\(V = \\pi \\int_{-2}^{2} (4 - x^2)^2 \\, dx\\)",
                sol("Expand", "V = \\pi \\int_{-2}^{2} (16 - 8x^2 + x^4) \\, dx"),
                sol("Integrate", "V = \\pi \\left[16x - \\frac{8x^3}{3} + \\frac{x^5}{5}\\right]_{-2}^{2}"),
                sol("Evaluate", "V = 2\\pi \\left(32 - \\frac{64}{3} + \\frac{32}{5}\\right)"),
                sol("Answer", "V = \\frac{512\\pi}{15}")
            ),
            time=270
        )
    end
end